---

- hosts: localhost
  gather_facts: false

  pre_tasks:

    - name: Install etcd on the first master for checking purposes
      yum: 
        name: etcd
      delegate_to: "{{groups['masters'] | first}}"

  tasks:

  - name: prepare admin user
    shell: oc adm policy add-scc-to-user privileged system:serviceaccount:default:default
    delegate_to: "{{groups['masters'] | first}}"

  - name: prepare admin user
    shell: oc adm policy add-scc-to-group anyuid system:authenticated
    delegate_to: "{{groups['masters'] | first}}"

- hosts: "{{groups['masters'] | first}}"
  gather_facts: false
  roles:
    - create_project
    - infra_check
    - infra_svc

#- hosts: nodes
#  gather_facts: false
#  serial: 1
#  roles:
#    - restart_nodes 


- hosts: "{{groups['masters'] | first}}"
  gather_facts: false
  tasks:
  - name: Final Check | pause for 1 minutes
    pause:
      minutes: 1

  - name: Final Check | Check that all pods returned after tests
    shell: "oc --config=/root/.kube/config get pods --all-namespaces|grep -v Running|grep -v Completed|grep -v NAMESPACE|grep -v NAME|grep -v READY| grep -v STATUS| grep -v RESTARTS| grep -v AGE"
    changed_when: 1==2
    register: finalstatus
    failed_when: finalstatus.stdout != ""
